language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install tox coveralls
# command to run tests
script:
  tox
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=py36
after_success:
  coveralls
